### ISSUE TITLE
[FEATURE][CULTUREINFO][SWAGGER] SWAGGER title 및 설명 내용 반영이 안되는 에러

### ISSUE THREAD

**Issue by shubiduba1212** [S-O-O-P/S-O-O-P-BackEnd-Admin#35]
##  💼 어떤 기능인가요?
> [Branch][본인 브랜치 이름]

## ✅ 작업 상세 내용
- [x] SwaggerConfig 클래스에 저장한 swagger info 정보가 정상적으로 반영이 안됩니다.

### SwaggerConfig 클래스에 저장한 swagger info 정보
![image](https://github.com/user-attachments/assets/8f94e4f9-e71d-4366-8c75-c2616788f9ac)

## 🐝 예상 결과
> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요
### 정상적으로 반영되어 있는  client swagger
![image](https://github.com/user-attachments/assets/416dbab5-d4b3-4410-9d5d-c65908819486)

###  SwaggerConfig 클래스에 저장한 swagger info 정보가 반영되지 않은 admin swagger
![image](https://github.com/user-attachments/assets/9af9922e-e6ac-43d4-b152-3665b08da041)

**Comment by neogoolboss** [comment]
@SpringBootApplication(scanBasePackages = "com.soop.pages")
@MapperScan(basePackages = "com.soop", annotationClass = Mapper.class)
public class SoopFinalProjectAdminApplication {

    public static void main(String[] args) {
        SpringApplication.run(SoopFinalProjectAdminApplication.class, args);
    }
    
    scanBasePackages에 com.soop 까지만 넣으시면 정상 작동합니다.
